services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nexa
      POSTGRES_PASSWORD: nexa
      POSTGRES_DB: nexa_erp
    ports:
      - "5432:5432"
    volumes:
      - nexa_postgres_data:/var/lib/postgresql/data

volumes:
  nexa_postgres_data:
