import { INestApplication } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import * as request from 'supertest';
import { createApp } from '../src/main';

const testUrl = process.env.DATABASE_URL_TEST;
if (!testUrl || !/_test(?:\?|$)/i.test(testUrl)) throw new Error('DATABASE_URL_TEST must point to a dedicated *_test database or schema');
const prisma = new PrismaClient({ datasources: { db: { url: testUrl } } });
describe('auth and tenancy (PostgreSQL)', () => {
  let app: INestApplication; let a: any; let b: any; let tenantA: string; let tenantB: string; let emailA: string;
  beforeAll(async () => { process.env.DATABASE_URL = testUrl; app = await createApp(); await app.init(); a = request.agent(app.getHttpServer()); b = request.agent(app.getHttpServer()); await prisma.membership.deleteMany(); await prisma.tenant.deleteMany(); await prisma.user.deleteMany(); });
  afterAll(async () => { await app.close(); await prisma.$disconnect(); });
  it('registers normalized user, tenant, owner membership, hash, and cookie', async () => { emailA = `a-${Date.now()}@example.com`; const r = await a.post('/api/auth/register').send({ name: 'A', email: emailA.toUpperCase(), password: 'password123', companyName: 'Acme Test' }).expect(201); expect(r.body.user.passwordHash).toBeUndefined(); expect(r.headers['set-cookie'][0]).toMatch(/HttpOnly/i); const u = await prisma.user.findUnique({ where: { email: emailA } }); expect(u?.passwordHash).not.toBe('password123'); expect(u?.passwordHash).toMatch(/^\$argon2/); const t = await prisma.tenant.findUnique({ where: { slug: 'acme-test' } }); tenantA = t!.id; expect(await prisma.membership.count({ where: { userId: u!.id, tenantId: t!.id, role: 'OWNER' } })).toBe(1); });
  it('rejects duplicate normalized emails with the same public conflict', async () => { const x = await b.post('/api/auth/register').send({ name: 'Dup', email: emailA.toUpperCase(), password: 'password123', companyName: 'Other' }).expect(409); expect(x.body.message).toBe('Email is already registered'); });
  it('logs in and protects me with a cookie', async () => { const r = await b.post('/api/auth/login').send({ email: emailA, password: 'password123' }).expect(200); expect(r.body.user.passwordHash).toBeUndefined(); const payload = JSON.parse(Buffer.from(r.headers['set-cookie'][0].match(/access_token=([^;]+)/)[1].split('.')[1], 'base64url').toString()); expect(Object.keys(payload).sort()).toEqual(expect.arrayContaining(['exp', 'iat', 'sub'])); expect(Object.keys(payload)).toHaveLength(3); await b.get('/api/auth/me').expect(200); const logout = await b.post('/api/auth/logout').expect(201); expect(logout.headers['set-cookie'][0]).toMatch(/access_token=;/); await request(app.getHttpServer()).get('/api/auth/me').expect(401); });
  it('uses the same generic failure for wrong password and unknown email', async () => { const x = await b.post('/api/auth/login').send({ email: emailA, password: 'wrongpass' }).expect(401); const y = await b.post('/api/auth/login').send({ email: 'missing@example.com', password: 'wrongpass' }).expect(401); expect(x.body).toEqual(y.body); });
  it('lists only memberships and enforces tenant context', async () => { const rb = await b.post('/api/auth/register').send({ name: 'B', email: `b-${Date.now()}@example.com`, password: 'password123', companyName: 'Beta Test' }).expect(201); const tb = await b.get('/api/tenants').expect(200); tenantB = tb.body[0].id; expect(tb.body).toHaveLength(1); expect((await a.get('/api/tenants')).body).toHaveLength(1); expect((await a.get('/api/tenant-context').set('X-Tenant-Id', tenantA)).status).toBe(200); expect((await a.get('/api/tenant-context').set('X-Tenant-Id', tenantB)).status).toBe(403); expect((await a.get('/api/tenant-context')).status).toBe(400); expect((await a.get('/api/tenant-context').set('X-Tenant-Id', 'bad')).status).toBe(400); expect((await a.get('/api/tenant-context').set('X-Tenant-Id', '00000000-0000-4000-8000-000000000000')).status).toBe(403); expect((await request(app.getHttpServer()).get('/api/tenant-context').set('X-Tenant-Id', tenantA)).status).toBe(401); expect(rb.body.user.passwordHash).toBeUndefined(); });
  it('rejects duplicate database membership and slug', async () => { const u = await prisma.user.findUniqueOrThrow({ where: { email: emailA } }); await expect(prisma.membership.create({ data: { userId: u.id, tenantId: tenantA, role: 'OWNER' } })).rejects.toMatchObject({ code: 'P2002' }); await expect(prisma.tenant.create({ data: { name: 'Duplicate', slug: 'acme-test' } })).rejects.toMatchObject({ code: 'P2002' }); });
  it('rolls back User, Tenant, and Membership when registration fails after User creation', async () => { const base = 'rollback-company'; await prisma.tenant.createMany({ data: Array.from({ length: 99 }, (_, i) => ({ name: 'Rollback', slug: i === 0 ? base : `${base}-${i + 1}` })) }); const email = `rollback-${Date.now()}@example.com`; await b.post('/api/auth/register').send({ name: 'Rollback', email, password: 'password123', companyName: 'Rollback Company' }).expect(409); expect(await prisma.user.count({ where: { email } })).toBe(0); expect(await prisma.tenant.count({ where: { slug: { startsWith: base } } })).toBe(99); expect(await prisma.membership.count({ where: { user: { email } } })).toBe(0); });
  it('allocates deterministic suffixes for repeated company names', async () => { const r = await b.post('/api/auth/register').send({ name: 'C', email: `c-${Date.now()}@example.com`, password: 'password123', companyName: 'Acme Test' }).expect(201); expect(r.body.user.passwordHash).toBeUndefined(); expect(await prisma.tenant.findUnique({ where: { slug: 'acme-test-2' } })).not.toBeNull(); });
});
